### ISSUE TITLE
[Service]: Deploy Backend of Registration Service

### ISSUE THREAD

**Issue by Ishad-M-I-M** [cse-mosip/deployments#11]
### Image name

mosipmoracse/registration-service

### Service name

registration-service

### Docker run command

```shell
docker run -e "DB_HOST=13.71.65.137" -e "DB_USER=pguser" -e "DB_NAME=registration-svc-pgdb" -e "DB_PW=pgpw" -e"BASE_URL=<url>" -e"DB_DIALECT=postgres" -e"JWT_SECRET=secret" -p <port-exposing>:8080 mosipmoracse/registration-service
```

### Database host

13.71.65.137

### Database name

registration-svc-pgdb

### Base url

registration-service

**Comment by akila-i** [comment]
Working on this
