### ISSUE TITLE
[Service]: Attendance Service

### ISSUE THREAD

**Issue by section117** [cse-mosip/deployments#16]
### Image name

ghcr.io/cse-mosip/attendance-service:latest

### Service name

attendance-service

### Docker run command

```shell
docker run -d -e SPRING_DATASOURCE_URL=jdbc:postgresql://20.246.154.149/attendance-svc-pgdb -e SPRING_DATASOURCE_USERNAME=pguser -e SPRING_DATASOURCE_PASSWORD=pgpw --name attendance-service ghcr.io/cse-mosip/attendance-service:latest
```

### Database host

20.246.154.149

### Database name

attendance-svc-pgdb

### Base url

attendance-service

**Comment by akila-i** [comment]
http://20.84.34.69/attendance-service/healthcheck
