### ISSUE TITLE
[Service]: Booking frontend

### ISSUE THREAD

**Issue by NethumL** [cse-mosip/deployments#7]
### Image name

ghcr.io/cse-mosip/booking-ui:latest

### Service name

booking-frontend

### Docker run command

```shell
docker run -p 8080:8080 ghcr.io/cse-mosip/booking-ui:latest
```

### Base url

/frontend-service/booking

**Comment by BanulaKumarage** [comment]
Frontend service is deployed at [http://104.211.229.43/frontend-service/booking/](http://104.211.229.43/frontend-service/booking/)
