### ISSUE TITLE
entry-service

### ISSUE THREAD

**Issue by dinushaAsamarakoon** [cse-mosip/deployments#9]
### Image name

mosipmoracse/university-entry-service

### Service name

entry-service

### Docker run command

```shell
docker build -t my-spring-app .

docker run -p 8080:8080 -e SPRING_DATASOURCE_URL=jdbc:postgresql://104.211.231.84:5432/entry-svc-pgdb -e SPRING_DATASOURCE_USERNAME=pguser -e SPRING_DATASOURCE_PASSWORD=pgpw -e SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver -e JWT_SECRET=4D6251655468576D5A7134743777217A25432A462D4A614E645266556A586E32 -e JWT_EXPIRATION=86400000 my-spring-app
```

### Database host

104.211.231.84

### Database name

entry-svc-pgdb

### Base url

entry-service

**Comment by BanulaKumarage** [comment]
@dinushaAsamarakoon @AyeshGK 

service is deployed in [http://104.211.229.43/entry-service/](http://104.211.229.43/entry-service/)

Used image: banula404/university-entry-service:latest
